<?php
declare(strict_types=1);

use Liquid\Blog\Block\Term;
use Liquid\Content\Block\Element\CopyBlock;

/**
 * https://www.techtarget.com/searchdatamanagement/definition/data-silo
 */
assert($this instanceof Term);
$term = $this->getTerm()
?>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('What are data silos?');
        $c->addContentLine('A data silo is a repository of data that is controlled by one department or business unit and isolated from the rest of an organization. Siloed data typically is stored in a standalone system and often is incompatible with other data sets. That makes it hard for users in other parts of the organization to access and use the data.');
        $c->addContentLine('Data silos can have technical, organizational or cultural roots. They tend to arise naturally in large companies because separate business units may operate independently and have their own goals, priorities and IT budgets. But any organization can end up with data silos if it does not have a well-planned {TERM}data management{/TERM} strategy.');
        echo $c->toHtml();
        ?>
    </div>
</div>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('The problem with data silos');
        $c->addContentLine('Data silos hinder business operations and the data analytics initiatives that support them. Silos limit the ability of executives to use data to manage business processes and make informed business decisions. They also prevent call center agents, sales reps and other operational workers from accessing relevant data about customers, products, supply chains and more.');
        echo $c->toHtml();
        ?>
    </div>
</div>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('How does Attlaz helps against data silos?');
        $c->addContentLine('Eliminating data silos enables an organization to manage and use data more effectively. It often also helps lower technology and data management costs. Attlaz allows following approaches to be used separately or in tandem to remove silos and connect data assets to better support business operations:');

        $c->addContentLine('Data integration', 'h3');
        $c->addContentLine('Integrating data silos with other systems is the most straightforward way to break them down. The most popular form of data integration is extract, transform and load ({TERM}ETL{/TERM}), which extracts data from source systems, consolidates it and loads it into a target system or application. Other {TERM}data integration techniques{/TERM} that can be used against silos include real-time integration, data virtualization and extract, load and transform, a variation on {TERM}ETL{/TERM}.');

        echo $c->toHtml();
        ?>
    </div>
</div>
