<?php
declare(strict_types=1);

/**
 * https://www.shopify.com/encyclopedia/fulfillment
 */

use Liquid\Blog\Block\Term;
use Liquid\Content\Block\Element\CopyBlock;

assert($this instanceof Term);
$term = $this->getTerm()
?>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('What is fulfillment?');
        $c->addContentLine('Fulfillment refers to the process of preparing and delivering a customer’s order. While catalog companies and larger operations typically are equipped to handle customer order fulfillment themselves, ecommerce companies and smaller businesses often hand over that aspect of the business to companies that specialize in fulfillment.');
        echo $c->toHtml();
        ?>
    </div>
</div>
