<?php
declare(strict_types=1);

// TODO: show Attlaz pim adapters

/**
 * https://www.plytix.com/what-is-pim?utm_medium=cpc&utm_source=google&utm_term=&utm_campaign=Dynamic+Search+Ads&hsa_acc=4807514456&hsa_cam=12863608236&hsa_grp=124456963394&hsa_ad=517456250054&hsa_src=g&hsa_tgt=dsa-1732584427351&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gclid=CjwKCAjwzNOaBhAcEiwAD7Tb6FyGq1jQtYbUgHJQ3qaaGMNExcd_vkRdSHzTF3HEoD80TM1a6GMjCBoCAvoQAvD_BwE
 */

use Liquid\Blog\Block\Term;
use Liquid\Content\Block\Element\CopyBlock;

assert($this instanceof Term);
$term = $this->getTerm()
?>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('What is PIM?');
        $c->addContentLine('PIM stands for Product Information Management. It refers to the process of handling all the data, content, and other material that you need to market and sell products. PIM also ensures that quality data is created for internal use and multichannel distribution.');
        echo $c->toHtml();
        ?>
    </div>
</div>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('What can you do with a PIM tool?');
        $c->addContentLine('There is a lot of data that supports a single product throughout its lifecycle. A good product information software is able to deal with incoming, outgoing, and cross-department product content.');
        $c->addContentList([
            'Centralize and sanitize scattered data.',
            'Enrich product descriptions and specifications.',
            'Track progress and product completion.',
            'Link images, documents, and media to products.',
            'Categorize products and files.',
            'Manage upstream data and prepare it for sales channels.',
            'Manage relationships between products.',
            'Create and publish product sheets.',
            'Build custom product feeds.',
            'Format product data for multi-channel syndication.',
            'Automate brand portal creation and maintenance.',
            $this->translate('Analyse') . ' product performance.',
            'Find everything in one central database.',
        ]);
        echo $c->toHtml();
        ?>
    </div>
</div>
