<?php
declare(strict_types=1);

/**
 * @var $this \Liquid\Framework\View\TemplateEngine
 * @var $block LinkTag
 */

use Liquid\Content\Block\Element\MarkupEngine\LinkTag;

$classes = [];

$classes[] = match ($block->getType()) {
    'button-big' => 'button size--large button-color-highlight',
    'button' => 'button button-color-highlight',
    default => 'link',
};

?>
<a href="<?= $block->getHref() ?>" <?= count($classes) > 0 ? 'class="' . implode(' ', $classes) . '"' : '' ?>>
    <span>
        <?= $block->getContent() ?>
    </span>
    <?php
    if ($block->showArrow()):
        ?>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"
             class="arrow-icon">
            <path d="M10 13L15 8L10 3" stroke="currentColor" stroke-width="2" stroke-linejoin="round"></path>
            <line x1="14" y1="8" x2="-8.74228e-08" y2="8" stroke="currentColor" stroke-width="2"></line>
        </svg>
    <?php
    endif;
    ?>
</a>
