<?php
declare(strict_types=1);

use Liquid\Blog\Block\Post;
use Liquid\Content\Block\Element\CopyBlock;

assert($this instanceof Post);



//- describe the different channels on which to get notifications
//- describe how to filter out the notifications
//- describe how to create a custom notification channel
?>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        echo $c->toHtml();
        ?>
    </div>
</div>


