<?php
declare(strict_types=1);

use Liquid\Blog\Block\Post;
use Liquid\Content\Block\Element\CopyBlock;

assert($this instanceof Post);


?>

<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('What has changed?', 'h2', 'what-has-changed');
        $c->addContentLine(" The new status page features an improved user experience that clearly shows the status of different services. We further broke down statuses in sub categories to allow a more granular view on the status of
                            services.");
        $c->addContentLine(' Our investments in Attlaz have improved our capabilities to detect more issues than ever before. However, some issues like external partner outages or scheduled maintenance are still beyond our control.');
        $c->addContentLine('We designed the new status page UI to surface these insights, so you can understand the exact causes of degraded services and react appropriately.');
        echo $c->toHtml();
        ?>
    </div>
</div>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('Improved visual indicators of service health and incident severity', 'h2', 'improved-visual-indicators');
        $c->addContentLine("One major challenge of our new design was displaying only the most relevant incident details and status indicators to you.");
        $c->addContentLine('We don’t want disruption in one service to show  your usage as degraded. At the same time, we never want want to show you “All Systems Operational” when a service issue is impacting your business.');
        $c->addContentLine('<div class="center">' . $this->renderLazyLoad('image/blog/improved-status-page/visual-indicators.png', 'Improved visual status indicators') . '</div>');
        echo $c->toHtml();
        ?>
    </div>
</div>
<div class="row ">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('Status breakdown by service', 'h2', 'status-breakdown-by-service');
        $c->addContentLine("While services are designed with a single core functionality in mind, it is possible that a partial functionality is not working as expected. To give a better understanding of what functionality is degraded we broke down services in several subtests.");
        $c->addContentLine('In the future we will keep investing in more issue detection and a further adding sub categories.');
        $c->addContentLine('<div class="center">' . $this->renderLazyLoad('image/blog/improved-status-page/status-by-service.png', 'Status breakdown by service') . '</div>');
        echo $c->toHtml();
        ?>
    </div>
</div>
<div class="row">
    <div class="column">
        <?php
        $c = new CopyBlock();
        $c->setHeaderTitle('Improve status tests', 'h2', 'improve-status-tests');
        $c->addContentLine('Under the hood we have re-written tests and added additional test to make sure to test all possible [issues] that might occur. This will give faster indication of possible issues and communicate with more transparency the functionality which is not working as expected.');
        $c->addContentLine('An upgraded and improved stack means faster indication of the current status');
        echo $c->toHtml();
        ?>
    </div>
</div>
