<?php
declare(strict_types=1);

/**
 * @var $this TemplateEngine
 * @var $block Template
 * @var $viewModel DemoCallToActionBlock
 */

use Liquid\Content\Block\Element\DemoCallToActionBlock;
use Liquid\Framework\View\Element\Template;
use Liquid\Framework\View\TemplateEngine;

$viewModel = $block->getViewModel();
?>

<section class="call-to-action-footer">
    <div class="container">
        <div class="wrapper">
            <div class="row">
                <div class="column col-2-2">
                    <copy-block types="header" title="<?= $viewModel->getTitle() ?>" title-tag="h4">
                        <?= $viewModel->getDescription() ?>
                        <div>
                            <link href="<?= $viewModel->getCallToActionPage() ?>"
                                  type="button" arrow="true">
                                <?= $viewModel->getCallToActionLabel() ?>
                            </link>
                        </div>
                    </copy-block>
                    <div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
