<?php
declare(strict_types=1);

/** @var $this \Liquid\Content\Block\TemplateBlock */

use Liquid\Content\Block\Element\MarkupEngine\PageSectionTag;

$properties = PageSectionTag::PROPERTIES;

$pageSectionTags = [];
foreach ($properties as $property) {
    if ($this->hasData($property)) {
        $value = $this->getData($property);
        if (!empty($value)) {
            $pageSectionTags[] = $property . '="' . $value . '"';
        }
    }
}
?>
<header>
    <page-section <?= implode(' ', $pageSectionTags) ?>>
        <?php
        $content = $this->getData('content');
        if ($content !== null) {
            // TODO: should we log that the content is empty?
            echo $content;
        }
        ?>
    </page-section>
</header>
