<?php
declare(strict_types=1);

use Liquid\Content\Block\TemplateBlock;

assert($this instanceof TemplateBlock);
?>
<header>
    <section class="background-medium background-angle">
        <div class="content">
            <div class="container">
                <div class="wrapper">
                    <div class="row">
                        <div class="column">
                            <div class="copy gap-large">
                                <div class="copy-header">
                                    <h1 class="copy-title">Introducing Beta</h1>
                                    <div class="copy-caption">Published Dec 01; 2021</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</header>
<main>
    <section>
        <div class="container">
            <div class="wrapper">
                <div class="row">
                    <div class="copy detail">
                        <div class="copy-content">
                            <div>
                                <h2>Title (H2)</h2>
                                <p>A cookie is a small file of letters and numbers downloaded on to your computer when you access certain websites. In general, cookies allow a website to recognise a user’s computer.</p>
                                <p>The most important thing to know about cookies placed by Attlaz is that they make our website a bit more user-friendly, for example, by remembering site preferences and language settings.</p>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </section>
</main>
