<?php
declare(strict_types=1);

use Liquid\Blog\Block\PostList;
use Liquid\Content\Block\Element\CopyBlock;
use Liquid\Content\Block\RelatedBlogPostsBlock;

assert($this instanceof RelatedBlogPostsBlock);

$blogPosts = $this->getBlogPosts();
?>
<!--<div style="font-weight: 700">700 One platform to streamline all workflows</div>-->
<!--<div style="font-weight: 600">600 One platform to streamline all workflows</div>-->
<!--<div style="font-weight: 500">500 One platform to streamline all workflows</div>-->
<!--<div style="font-weight: 400">400 One platform to streamline all workflows</div>-->
<!--<div style="font-weight: 300">300 One platform to streamline all workflows</div>-->
<page-section>
    <div class="row rowGapLarge">
        <div class="column col-1">
            <?php
            $header = $this->getLayout()->createBlock(CopyBlock::class, '', ['types' => '']);
            $header->setHeaderTitle($this->title, 'h3');
            echo $header;
            ?>
        </div>
        <?php
        $postListBlock = $this->getLayout()->createBlock(PostList::class);
        $postListBlock->setPosts($blogPosts);
        echo $postListBlock->toHtml();
        ?>
    </div>

</page-section>
