<?php
declare(strict_types=1);

/**
 * Resize SVG: https://editor.method.ac/
 */

use Liquid\Content\Block\TemplateBlock;

assert($this instanceof TemplateBlock);

$customers = [
    'VerlichtingBE' => 'verlichtingbe.svg',
    'UC Experts'    => 'ucexperts.svg',
    'Quicke'        => 'quicke.svg',
    'Audiosense'    => 'audiosense.svg',
    'Catlar'        => 'catlar.svg',
    //    'Baldwin'       => 'baldwin.svg',
    'A Suivre'      => 'asuivre.svg',

];
?>
<section class="trusted-by none">
    <div class="container">
        <div class="wrapper">
            <div class="row">
                <div class="logos">
                    <?php foreach ($customers as $customer => $logo):
                        $logoUrl = $this->getResolver()->getAssetUrl('/image/customers/' . $logo);
                        ?>
                        <div>
                            <img src="<?= $logoUrl ?>" alt="Logo <?= $customer ?>" loading="lazy" width="200px" height="150px"/>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</section>
