<?php
declare(strict_types=1);
$showBlock = false;
if (!$showBlock) {
    return;
}

use Liquid\Content\Block\Element\CopyBlock;
use Liquid\Content\Block\TemplateBlock;

assert($this instanceof TemplateBlock);

$customers = [
    'VerlichtingBE' => 'verlichtingbe.svg',
    'UC Experts' => 'ucexperts.svg',
    'Quicke' => 'quicke.svg',
    'Audiosense' => 'audiosense.svg',
    //    'Baldwin'       => 'baldwin.svg',
    'Catlar' => 'catlar.svg',
    'A Suivre' => 'asuivre.svg',

];
?>
<section class="background-dark trusted-by">
    <div class="container">
        <div class="wrapper">
            <div class="row">
                <div class="column col-1">
                    <?php
                    $b = new CopyBlock('center detail');
                    $b->setHeaderTitle('Trusted by innovative organizations');
                    echo $b->toHtml();
                    ?>
                </div>
                <div class="column logos">
                    <?php foreach ($customers as $customer => $logo): ?>
                        <div>
                            <?= $this->renderLazyLoad('/image/customers/' . $logo, $customer) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</section>
