<?php
declare(strict_types=1);
/** @var FaqBlock $this */

use Liquid\Content\Block\Element\FaqBlock;

$topics = $this->getTopics();
?>
<div class="faq">
    <?php
    $i = 0;
    foreach ($topics as $topic) {
        ?>
        <div class="faq-item">
            <div class="faq-question">
                <?= $topic['title'] ?>
            </div>
            <div class="faq-answer-wrapper">
                <div class="faq-answer-text">
                    <?= $topic['content'] ?>
                </div>
            </div>
        </div>
        <?php
        $i++;
    }
    ?>
</div>
