<?php
declare(strict_types=1);


/**
 * @var $this TemplateEngine
 * @var $block Template
 * @var $escaper Escaper
 * @var $segment LocaleHelper
 * @var $logger LoggerInterface
 */

use Liquid\Content\Helper\LocaleHelper;
use Liquid\Content\ViewModel\HtmlHead;
use Liquid\Framework\Escaper;
use Liquid\Framework\View\Element\Template;
use Liquid\Framework\View\TemplateEngine;
use Psr\Log\LoggerInterface;

$headBlock = $block->getLayout()->getBlock('head');
if ($headBlock instanceof Template) {
    /** @var HtmlHead $viewModel */
    $viewModel = $headBlock->getViewModel();
    $scripts = $viewModel->getScripts();

    foreach ($scripts as $script) {
        echo $viewModel->renderScript($script);
    }
}
