<?php
declare(strict_types=1);

/**
 * @var $this TemplateEngine
 * @var $block Template
 * @var $escaper Escaper
 * @var $segment LocaleHelper
 * @var $logger LoggerInterface
 */
/** @var BaseViewModel $viewModel */

use Liquid\Content\Helper\LocaleHelper;
use Liquid\Content\Helper\ViewableEntity;
use Liquid\Content\ViewModel\BaseViewModel;
use Liquid\Content\ViewModel\Navigation;
use Liquid\Framework\Escaper;
use Liquid\Framework\View\Element\Template;
use Liquid\Framework\View\TemplateEngine;
use Psr\Log\LoggerInterface;

$viewModel = $block->getViewModel('base');
/** @var Navigation $navigationViewModel */
$navigationViewModel = $block->getViewModel('navigation');

$resolver = $viewModel->getResolver();

$helper = $this->helper(ViewableEntity::class);
?>
<header class="site-header">
    <div class="container">
        <div class="wrapper">
            <div class="logo">
                <a href="<?= $helper->getUrl('home') ?>" aria-label="Attlaz">
                    <img height="30px" width="130px" class="logo-light"
                         src="<?= $resolver->getFrontendFileImageUrl('asset/logo-light.svg')->url ?>" alt="Attlaz">
                    <img height="30px" width="130px" class="logo-dark"
                         src="<?= $resolver->getFrontendFileImageUrl('asset/logo.svg')->url ?>" alt="Attlaz">
                </a>
            </div>

            <nav class="navigation">
                <?php foreach ($navigationViewModel->navigation as $navItem): ?>
                    <div class="nav-item" <?= ($navItem['type'] === 'dropdown') ? 'aria-haspopup="true" aria-expanded="false"' : '' ?>>

                        <?php if ($navItem['type'] === 'link'): ?>
                            <div class="nav-item-link">
                                <a href="<?= $navItem['link'] ?>"><?= $navItem['title'] ?></a>
                            </div>
                        <?php else: ?>
                            <div class="nav-item-toggle">
                                <?= $navItem['title'] ?>
                            </div>
                        <?php endif ?>

                        <?php if ($navItem['type'] === 'dropdown'): ?>
                            <div class="nav-item-dropdown">
                                <div class="sections">
                                    <?php foreach ($navItem['subsections'] as $navItemSubSection): ?>
                                        <div class="section">
                                            <?php if (isset($navItemSubSection['title'])): ?>
                                                <div class="title"><?= $navItemSubSection['title'] ?></div>
                                            <?php endif; ?>

                                            <nav class="items">
                                                <?php foreach ($navItemSubSection['items'] as $navItemSubSectionItem): ?>
                                                    <div class="item">
                                                        <a class="item-link"
                                                           href="<?= $navItemSubSectionItem['link'] ?>"
                                                            <?= isset($navItemSubSectionItem['target']) ? 'target="' . $navItemSubSectionItem['target'] . '"' : '' ?>
                                                            <?= isset($navItemSubSectionItem['rel']) ? 'rel="' . $navItemSubSectionItem['rel'] . '"' : '' ?>
                                                        >
                                                            <div class="item-icon">
                                                                <?= $viewModel->renderSVG($navItemSubSectionItem['icon']) ?>
                                                                <!--                                                                <img loading="lazy"-->
                                                                <!--                                                                     src="-->
                                                                <?php //= $navItemSubSectionItem['icon'] ?><!--"-->
                                                                <!--                                                                     alt="-->
                                                                <?php //= $navItemSubSectionItem['title'] ?><!--">-->
                                                            </div>
                                                            <div class="item-text">
                                                                <div class="item-text-title"><?= $navItemSubSectionItem['title'] ?></div>
                                                                <?php if (isset($navItemSubSectionItem['description'])): ?>
                                                                    <div class="item-text-description"><?= $navItemSubSectionItem['description'] ?></div>
                                                                <?php endif; ?>
                                                            </div>

                                                        </a>
                                                    </div>
                                                <?php endforeach; ?>
                                            </nav>
                                        </div>
                                    <?php endforeach; ?>
                                    <?php if (isset($navItem['footer'])): ?>
                                        <div class="section">
                                            <div class="items">
                                                <div class="item">
                                                    <a class="item-link" href="<?= $navItem['footer']['link'] ?>">
                                                        <div class="item-icon large">
                                                            <img loading="lazy" src="<?= $navItem['footer']['icon'] ?>"
                                                                 alt="<?= $navItem['footer']['title'] ?>">
                                                        </div>
                                                        <div class="item-text">
                                                            <div class="item-text-title"><?= $navItem['footer']['title'] ?></div>
                                                            <div class="item-text-description"><?= $navItem['footer']['description'] ?></div>
                                                        </div>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>


                            </div>
                        <?php endif ?>
                    </div>
                <?php endforeach; ?>


                <div class="sub-navigation">
                    <div class="wrapper-container">
                        <div class="wrapper">

                        </div>
                    </div>
                </div>
                <div class="overlay"></div>
            </nav>
            <div class="links gap--1">
                <a href="<?= $viewModel->getConfig()->getValue('external/url/app') ?>" target="_blank" rel="noopener"
                   class="link hide md:show signin">Sign in</a>
                <a href="<?= $viewModel->getEntityUrl('demo') ?>" class="try hide md:show link">Book a demo</a>
                <div class="menu-button link">
                    <img width="24" height="24" loading="lazy"
                         src="<?= $resolver->getFrontendFileImageUrl('asset/image/menu.svg')->url ?>" alt="Menu">
                </div>

            </div>
        </div>
    </div>
</header>
