<?php
declare(strict_types=1);


use Liquid\Blog\Block\Category;
use Liquid\Blog\Block\PostList;
use Liquid\Content\Block\Element\CopyBlock;
use Liquid\Content\Block\Element\DemoCallToActionBlock;
use Liquid\Content\Block\Element\TagBar;

assert($this instanceof Category);
$category = $this->getCategory();
$posts = $this->getPosts();
?>

<page-header>

    <div class="row">
        <div class="column col-3-1">
            <?php
            $hero = new CopyBlock('header');
            $hero->setHeaderTitle($category->title_long, 'h1');
            $hero->setContent($category->metaDescription);
            echo $hero->toHtml();
            ?>
            <div>
                <?= $this->renderLazyLoad('hero_term.png', $category->title_long, new \Liquid\Content\Model\Asset\AssetSizeInstruction(520, 520)) ?>
            </div>
        </div>
    </div>
</page-header>


<main>
    <section>
        <div class="container">
            <div class="wrapper">


                <div class="row rowGapExtraLarge">
                    <?php
                    /** @var TagBar $categoriesTagBar */
                    $categoriesTagBar = $this->getLayout()->createBlock(TagBar::class);
                    $categoriesTagBar->setTags($this->getCategories());
                    $categoriesTagBar->setCurrent($category);
                    $categoriesTagBar->setAllTarget($this->getResolver()->getUrl('blog'));
                    echo $categoriesTagBar->toHtml();


                    /** @var PostList $postListBlock */
                    $postListBlock = $this->getLayout()->createBlock(PostList::class);
                    $postListBlock->setPosts($posts);
                    echo $postListBlock->toHtml();


                    ?>
                </div>
            </div>
        </div>

    </section>
    <?php
    $callToAction = $this->getLayout()->createBlock(DemoCallToActionBlock::class, 'call-to-action');
    assert($callToAction instanceof DemoCallToActionBlock);
    echo $callToAction->toHtml();
    ?>
</main>
