<?php
declare(strict_types=1);


/**
 * @var $this TemplateEngine
 * @var $block Template
 * @var $viewModel Term
 * @var $baseViewModel BaseViewModel
 */

use Liquid\Blog\Model\ViewModel\Term;
use Liquid\Content\ViewModel\BaseViewModel;
use Liquid\Framework\View\Element\Template;
use Liquid\Framework\View\TemplateEngine;

$viewModel = $block->getViewModel('', Term::class);
$baseViewModel = $block->getViewModel('base', BaseViewModel::class);

$term = $viewModel->getTerm();
?>
<page-header>
    <div class="row">
        <div class="column col-2-1">
            <copy-block title="<?= $term->termLong ?>" title-tag="h1">

            </copy-block>
            $hero->toHtml();
            ?>
            <div>
                <?= $baseViewModel->renderLazyLoad('hero_term.png', $term->term, null, false) ?>
            </div>
        </div>
    </div>
</page-header>
<main>
    <page-section>
        <div class="row">
            <?= $block->getChildHtml('content') ?>
        </div>
    </page-section>
    <?= $block->getChildHtml('use_cases') ?>
</main>
