<?php
declare(strict_types=1);

/**
 * @var $block Template
 * @var $this TemplateEngine
 */

use Liquid\Admin\ViewModel\DebugViewModel;
use Liquid\Framework\View\Element\Template;
use Liquid\Framework\View\TemplateEngine;

$viewModel = $block->getViewModel('debug', DebugViewModel::class);

$entities = $viewModel->x();
foreach ($entities as $entity) {
    echo '<div>' . $entity->getUrlPath() . '</div>';
}
