<?php
declare(strict_types=1);

use Liquid\Core\Model\Result\Page;

assert($this instanceof Page);

/**
 * @var $htmlAttributes string
 * @var $headContent string
 * @var $bodyAttributes string
 * @var $layoutContent string
 */
?>
<!DOCTYPE html>
<html <?= $htmlAttributes ?>>
    <?= $headContent ?>
    <body <?= $bodyAttributes ?>>
        <!-- Google Tag Manager (noscript) -->
        <noscript>
            <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MMTP4XJ" height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
        <!-- End Google Tag Manager (noscript) -->
        <?= $layoutContent ?>
    </body>
</html>
