<?php
declare(strict_types=1);

use Liquid\Core\Model\Layout\Block;

assert($this instanceof Block);
?>

<section class="cookies">
    <div class="cookies-container">
        <div class="cookies-wrapper">
            <div class="text">
                By clicking &quot;Accept&quot;, you agree to the storing of cookies on your device to enhance site navigation, <?= $this->translate('analyse') ?> site usage, and assist in our marketing efforts.
            </div>
            <div class="buttons">
                <div class="cookies-accept button button-color-highlight center">Accept</div>
                <div class="cookies-settings button button-color-white-border center">Settings</div>
            </div>
        </div>
    </div>
</section>
<footer>
    <section class="background-ocean">
        <div class="content">
            <div class="container">
                <div class="wrapper">
                    <div class="row">
                        <div class="column col-footer">
                            <div class="column">
                                <div class="logo">
                                    <a href="<?= $this->getResolver()->getPageUrl('home') ?>" aria-label="Attlaz">
                                        <img height="30px" width="130px" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/logo-white.svg')->url ?>" alt="Attlaz">
                                    </a>
                                </div>
                            </div>
                            <div class="column">
                                <div>
                                    <div class="title">Products</div>
                                    <ul>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('products/integrate') ?>">Integrate</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('products/automate') ?>">Automate</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('products/visualise') ?>">Visualise</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="column">
                                <div>
                                    <div class="title">About</div>
                                    <ul>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('about') ?>">About</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('careers') ?>">Careers</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('partners') ?>">Partners</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('contact') ?>">Contact us</a></li>
                                        <?php
                                        $showEnvironment = false;
                                        if ($showEnvironment):
                                            ?>

                                            <li><a href="<?= $this->getResolver()->getPageUrl('environment') ?>">Environment</a></li>
                                        <?php
                                        endif;
                                        ?>
                                    </ul>
                                </div>
                            </div>
                            <div class="column">
                                <div>
                                    <div class="title">Solutions</div>
                                    <ul>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('use-cases/ecommerce') ?>">Ecommerce</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('use-cases/marketing') ?>">Marketing</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('use-cases/data-migration') ?>">Data migration</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="column">
                                <div>
                                    <div class="title">Resources</div>
                                    <ul>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('blog') ?>">Blog</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('docs') ?>">Documentation</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('docs/api') ?>">API reference</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('status') ?>" target="_blank" rel="noopener">Platform status</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('app') ?>" target="_blank" rel="noopener">Dashboard</a></li>
                                        <li><a href="<?= $this->getResolver()->getPageUrl('support') ?>">Help Center</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container container-bottom">
                <div class="wrapper">
                    <div class="row row-bottom">
                        <div class="column col-1-1-1">
                            <div class="copyright">&copy; <?= date('Y') ?> Attlaz. All rights reserved</div>
                            <div class="legal">
                                <ul class="flex-medium">
                                    <li><a href="<?= $this->getResolver()->getPageUrl('legal/privacy') ?>">Privacy Policy</a></li>
                                    <li><a href="<?= $this->getResolver()->getPageUrl('legal/terms') ?>">Terms and Conditions</a></li>
                                    <li><a href="<?= $this->getResolver()->getPageUrl('legal/cookies') ?>">Cookies</a></li>
                                </ul>
                            </div>
                            <div class="social">
                                <div class="flex-medium">
                                    <div>
                                        <a aria-label="Twitter" href="https://twitter.com/attlazhq" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/twitter.svg')->url ?>" alt="Twitter">
                                        </a>
                                    </div>
                                    <div>
                                        <a aria-label="Facebook" href="https://www.facebook.com/attlaz" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/facebook.svg')->url ?>" alt="Facebook">
                                        </a>
                                    </div>
                                    <div>
                                        <a aria-label="Instagram" href="https://www.instagram.com/attlazhq/" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/instagram.svg')->url ?>" alt="Instagram">
                                        </a>
                                    </div>
                                    <div style="display: none">
                                        <a aria-label="Youtube" href="https://twitter.com/Attlaz_" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/youtube.svg')->url ?>" alt="Youtube">
                                        </a>
                                    </div>
                                    <div>
                                        <a aria-label="LinkedIn" href="https://www.linkedin.com/company/attlaz" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/linkedin.svg')->url ?>" alt="Linkedin">
                                        </a>
                                    </div>
                                    <div style="display: none">
                                        <a aria-label="Dev.To" href="https://dev.to/attlaz" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/dev-dot-to.svg')->url ?>" alt="Dev.To">
                                        </a>
                                    </div>
                                    <div>
                                        <a aria-label="GitHub" href="https://github.com/Attlaz-Platform" target="_blank" rel="noopener">
                                            <img width="14" height="14" loading="lazy" src="<?= $this->getResolver()->getFrontendFileImageUrl('asset/image/social/github.svg')->url ?>" alt="GitHub">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</footer>
