<?php
declare(strict_types=1);

/**
 * @var $this TemplateEngine
 * @var $block Template
 */

use Liquid\Blog\Model\ViewModel\PostViewModel;
use Liquid\Content\Helper\StringHelper;
use Liquid\Content\Model\Asset\AssetSizeInstruction;
use Liquid\Content\Model\Asset\AssetSizeInstructionCrop;
use Liquid\Content\ViewModel\BaseViewModel;
use Liquid\Framework\View\Element\Template;
use Liquid\Framework\View\TemplateEngine;


/** @var BaseViewModel $baseViewModel */
$baseViewModel = $block->getViewModel('base');

$postViewModel = $block->getViewModel('', PostViewModel::class);

$post = $postViewModel->getPost();
$category = $postViewModel->getPostCategory();


$showBreadcrumbs = false;
?>
<page-header>
    <div class="row">

        <div class="column mb-6">
            <?php if ($showBreadcrumbs): ?>
            <div class="column">
                <div class="blog-breadcrumbs-wrapper">
                    <div class="blog-breadcrumbs">
                        <a href="<?= $baseViewModel->getEntityUrl('blog') ?>">Blog</a> /
                        <a href="<?= $baseViewModel->getUrl()->getUrl($category->getUrlPath()) ?>"><?= $category->metaTitle ?></a>
                        /
                        <span><?= $post->metaTitle ?></span>
                    </div>
                </div>
                <?php endif ?>
            </div>


            <copy-block title="<?= $baseViewModel->getEscaper()->escapeHtmlAttribute($post->metaTitle) ?>"
                        title-tag="h1"></copy-block>
            <div class="blog-header-image">
                <?= $baseViewModel->renderLazyLoad($post->image, $post->metaTitle, new AssetSizeInstruction(1231, 553, AssetSizeInstructionCrop::Center, 50), false) ?>
            </div>
        </div>
        <div class="column">

        </div>
    </div>
</page-header>
<main>
    <page-section style="no-padding">
        <div class="row">
            <div class="column col-1-1-1 info">

                <?php
                if (false) {
                    ?>
                    <div class="blog-date-wrapper">
                        <div class="bold">Published</div>
                        <div><?= StringHelper::formatDate($post->publishDate) ?></div>
                    </div>
                    <div></div>
                    <?php
                }
                ?>

            </div>


        </div>
        <div class="row">
            <div class="wrapper-sidebar">
                <div class="sidebar-left">
                    <!--                    <div class="duration">-->
                    <!--                        Read duration-->
                    <!--                    </div>-->
                    <div class="blog-author-wrapper">
                        <div class="bold"><?= $post->author->name ?></div>
                        <div class="light fs-small"><?= $post->author->role ?></div>
                    </div>
                    <div class="headers">
                        <div class="heading">
                            Content
                        </div>
                        <ul>
                            <?php
                            foreach ($postViewModel->getPostAnchors() as $anchor) {
                                ?>
                                <li><a href="<?= $anchor['target'] ?>"><?= $anchor['label'] ?></a></li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                    <div class="tags">
                        <div class="heading">Tags</div>
                        <div class="blog-card-tags-wrapper">
                            <div class="blog-card-tags">
                                <?php
                                $tags = $postViewModel->getPostTags();
                                foreach ($tags as $tag):
                                    ?>
                                    <div class="tag">
                                        <a href="<?= $baseViewModel->getResolver()->getUrl($tag->getUrlPath()) ?>"><?= $tag->metaTitle ?></a>
                                    </div>
                                <?php
                                endforeach;
                                ?>
                            </div>
                        </div>
                    </div>
                    <!--                    <div class="share">-->
                    <!--                        <div class="heading">Share the article</div>-->
                    <!--                    </div>-->
                </div>
                <div class="sidebar-main">
                    <div class="intro">
                        <copy-block types="header">
                            <?= $post->intro ?>
                        </copy-block>
                    </div>
                    <?= $postViewModel->getPostContent() ?>
                </div>
            </div>
        </div>
    </page-section>
</main>
