<?php
declare(strict_types=1);

use Liquid\Content\Block\Element\CopyBlock;
use Liquid\Content\Block\Element\DemoCallToActionBlock;

assert($this instanceof DemoCallToActionBlock);
?>

<section class="call-to-action-footer">
    <div class="container">
        <div class="wrapper">
            <div class="row">
                <div class="column col-2-2">
                    <?php
                    $left = new CopyBlock('header');
                    $left->setHeaderTitle($this->getTitle(), 'div');
                    echo $left->toHtml();

                    $right = new CopyBlock();
                    $right->addContentLine($this->getDescription());
                    $right->addContentLine('<a href="' . $this->getCallToActionPage() . '" class="button arrow">' . $this->getCallToActionLabel() . '</a>');
                    echo $right->toHtml();

                    ?>
                </div>
            </div>
        </div>
    </div>
</section>
