<?php
declare(strict_types=1);

use Liquid\Blog\Block\PostList;
use Liquid\Content\Block\Element\CopyBlock;
use Liquid\Content\Model\Asset\AssetSizeInstruction;
use Liquid\Content\Model\Asset\AssetSizeInstructionCrop;

assert($this instanceof PostList);

$posts = $this->getPosts();

if (count($posts) === 0):
    ?>
    <div class="column">
        <?php
        $x = $this->getLayout()->createBlock(CopyBlock::class, '', ['types' => 'new center card card--paddingMedium card--theme-aqua']);
        $x->setHeaderTitle('No posts found');
        $x->setContent('Whoops, there should be posts here.');
        $x->setFooter('<div><link arrow="true" page="blog">Go to the blog overview</link></div>');
        echo $x->toHtml();
        ?>
    </div>
<?php
else:
    ?>


    <div class="blog-list column col-1-1-1">
        <?php
        foreach ($posts as $post) {
            ?>
            <div class="blog-item-wrapper">
                <a href="<?= $this->getResolver()->getUrl($post->getUrlPath()) ?>" class="blog-content-card">
                    <div class="blog-thumbnail-wrapper">
                        <?php if (!empty($post->image)) {
                            echo $this->renderLazyLoad($post->image, $post->metaTitle, new AssetSizeInstruction(339, 187, AssetSizeInstructionCrop::Center));
                        }
                        ?>
                    </div>
                    <div class="blog-content-wrapper">
                        <div class="blog-post-info">
                            <?php
                            $category = $this->getCategory($post);
                            if ($category !== null):
                                ?>
                                <div class="category">
                                    <?= $category->metaTitle ?>
                                </div>
                            <?php
                            endif;
                            ?>
                            <div class="separator"></div>
                            <div class="read-duration">
                                <?= $this->estimateReadingTime($post) ?> min read
                            </div>
                        </div>
                        <div class="blog-card-heading">
                            <?= $post->metaTitle ?>
                        </div>
                        <div class="blog-post-intro">
                            <?= $post->intro ?>
                        </div>
                    </div>
                </a>


            </div>
            <?php
        }
        ?>
    </div>

<?php
endif;
